title: Smart Mirror
email: pedro.teix@ua.pt
description: >- # this means to ignore newlines until "baseurl:"
  Make life easier

baseurl: "" # the subpath of your site, e.g. /blog

# Paths
assets: '/assets'
timesheet: ''

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-toc
#  - jekyll-paginate
#  - jekyll-sitemap
#  - jekyll-feed
#  - jekyll-seo-tag
#  - jekyll-archives

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
