title: Smart Mirror
email: pedro.teix@ua.pt
description: >- # this means to ignore newlines until "baseurl:"
  Make your life easier

baseurl: "https://esp30.github.io/smartMirrorDoc/" 

# Paths
assets: 'assets'
timesheet: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vT8Aul5M6djEn5v0aWz0-NZ0BTJEsLM32V1V56jiH8lLEZDLp3RnniAGZndBNU9iAkM1oAwsiV4BTim/pubhtml?widget=true&amp;headers=false'

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-toc
#  - jekyll-paginate
#  - jekyll-sitemap
#  - jekyll-feed
#  - jekyll-seo-tag
#  - jekyll-archives

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
